#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow", "requests"]
# ///
"""gen_weather_icons.py — Download OWM weather icons and convert to 1-bit C arrays.

Downloads all 18 OWM weather icons at @2x (100×100 RGBA PNG), scales to ICON_SIZE×ICON_SIZE,
alpha-composites on white, thresholds to 1-bit, and writes main/weather_icons_bmp.h with
packed C byte arrays for Paint_SetPixel rendering on the 7.5" V2 e-paper display.

Usage (from repo root):
    uv run tools/gen_weather_icons.py
    uv run tools/gen_weather_icons.py --size 48
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

import requests
from PIL import Image

ICON_CODES = [
    "01d",
    "01n",
    "02d",
    "02n",
    "03d",
    "03n",
    "04d",
    "04n",
    "09d",
    "09n",
    "10d",
    "10n",
    "11d",
    "11n",
    "13d",
    "13n",
    "50d",
    "50n",
]

OWM_ICON_URL = "https://openweathermap.org/img/wn/{}@2x.png"


def download_icon(code: str) -> bytes:
    url = OWM_ICON_URL.format(code)
    print(f"  Downloading {url}", end=" ", flush=True)
    resp = requests.get(url, timeout=15)
    resp.raise_for_status()
    print(f"[{len(resp.content)} bytes]")
    return resp.content


def png_to_1bit(png_data: bytes, size: int) -> list[int]:
    """Convert RGBA PNG to a packed 1-bit bitmap (MSB first, row-major).

    Uses the alpha channel: opaque pixels (alpha > 30) → bit=1 (BLACK).
    Transparent pixels → bit=0 (skip/WHITE).  This preserves the full icon
    shape regardless of icon colour (yellow sun, orange cloud, etc.).
    Returns size * ceil(size/8) byte values.
    """
    img = Image.open(io.BytesIO(png_data)).convert("RGBA")

    # Extract alpha channel and resize — shape only, colour-independent
    alpha = img.split()[3]
    alpha = alpha.resize((size, size), Image.LANCZOS)

    pixels = list(alpha.tobytes())
    bytes_per_row = (size + 7) // 8
    result: list[int] = []

    for row in range(size):
        for col_byte in range(bytes_per_row):
            byte = 0
            for bit in range(8):
                col = col_byte * 8 + bit
                if col < size and pixels[row * size + col] > 30:
                    byte |= 0x80 >> bit
            result.append(byte)

    return result


def c_array_name(code: str) -> str:
    return f"icon_{code.replace('-', '_')}"


def generate_header(bitmaps: dict[str, list[int]], size: int, out_path: Path) -> None:
    bytes_per_row = (size + 7) // 8
    bytes_per_icon = size * bytes_per_row

    lines: list[str] = [
        "// AUTO-GENERATED by tools/gen_weather_icons.py — DO NOT EDIT MANUALLY",
        "// Re-generate: uv run tools/gen_weather_icons.py",
        "//",
        "// 1-bit packed bitmaps (MSB first, row-major) for each OWM weather icon.",
        "// bit=1 → BLACK pixel   bit=0 → skip (background stays WHITE)",
        "",
        "#ifndef WEATHER_ICONS_BMP_H",
        "#define WEATHER_ICONS_BMP_H",
        "",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        f"#define WEATHER_ICON_W              {size}",
        f"#define WEATHER_ICON_H              {size}",
        f"#define WEATHER_ICON_BYTES_PER_ROW  {bytes_per_row}",
        f"#define WEATHER_ICON_BYTES          {bytes_per_icon}",
        "",
    ]

    for code, data in bitmaps.items():
        name = c_array_name(code)
        lines.append(f"// OWM icon: {code}")
        lines.append(f"static const uint8_t {name}[{bytes_per_icon}] = {{")
        for i in range(0, len(data), bytes_per_row):
            chunk = data[i : i + bytes_per_row]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")

    lines += [
        "/**",
        " * @brief Return the pre-baked 1-bit bitmap for an OWM icon code.",
        ' * @param icon_code  OWM icon string, e.g. "01d", "10n"',
        " * @return Pointer to WEATHER_ICON_BYTES bytes, or NULL if unknown.",
        " */",
        "static inline const uint8_t *weather_icon_bitmap(const char *icon_code) {",
        "    if (!icon_code || icon_code[0] == '\\0') return NULL;",
    ]
    for code in bitmaps:
        name = c_array_name(code)
        lines.append(f'    if (strcmp(icon_code, "{code}") == 0) return {name};')
    lines += [
        "    return NULL;",
        "}",
        "",
        "#endif // WEATHER_ICONS_BMP_H",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {out_path}")
    print(
        f"  {len(bitmaps)} icons · {size}×{size}px · {bytes_per_icon} bytes each "
        f"· {len(bitmaps) * bytes_per_icon} bytes total"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate OWM weather icon C header")
    parser.add_argument(
        "--size",
        type=int,
        default=48,
        help="Icon size in pixels, must be multiple of 8 (default: 48)",
    )
    args = parser.parse_args()

    if args.size % 8 != 0:
        print(
            f"Error: --size must be a multiple of 8 (got {args.size})", file=sys.stderr
        )
        sys.exit(1)

    repo_root = Path(__file__).parent.parent
    out_path = repo_root / "main" / "weather_icons_bmp.h"

    print(f"Generating {args.size}×{args.size} weather icon bitmaps → {out_path}")
    print(f"Fetching {len(ICON_CODES)} icons from OpenWeatherMap...\n")

    bitmaps: dict[str, list[int]] = {}
    for code in ICON_CODES:
        try:
            png_data = download_icon(code)
            bitmaps[code] = png_to_1bit(png_data, args.size)
        except Exception as e:
            print(f"  ERROR for {code}: {e}", file=sys.stderr)
            sys.exit(1)

    generate_header(bitmaps, args.size, out_path)


if __name__ == "__main__":
    main()
